
FROM tensorflow/tensorflow:2.1.0-gpu-py3
WORKDIR /kw_resources/dogs_and_cats_small
RUN pip install --upgrade pip
RUN pip install tensorflow==1.14
RUN pip install keras==2.3.1
RUN pip install numpy==1.16.6
RUN pip install matplotlib==3.3.2
CMD python3 /kw_resources/dogs_and_cats_small/main.py


FROM tensorflow/tensorflow:2.1.0-gpu-py3
WORKDIR /kw_resources/dogs_and_cats_small
RUN pip install --upgrade pip
RUN pip install tensorflow==2.1.0
RUN pip install keras==2.3.1
RUN pip install numpy
RUN pip install matplotlib
CMD python3 /kw_resources/dogs_and_cats_small/main.py



FROM tensorflow/tensorflow:2.1.0-gpu-py3
WORKDIR /kw_resources/dogs_and_cats_small
RUN pip install --upgrade pip
RUN pip install tensorflow==2.1.0
RUN pip install keras==2.3.1
RUN pip install pandas
RUN pip install seaborn
RUN pip install scikit-learn
RUN pip install numpy
RUN pip install matplotlib
CMD python3 /kw_resources/dogs_and_cats_small/MNIST_CNN.py